### PR TITLE
Arm64e Support

### PR DESCRIPTION
**Pull request by itaybre**

### CODE REVIEW

**Comment by blunden** [comment]
You should probably mention where HookUtil comes from.

My guess would be the repo below (no license specified), although there is also a second repo with AGPL licensed code that is very similar to that repo but is likely based on it, not the other way around. If it's based on the latter, its license is incompatible but use of code from the former is probably fine.

https://github.com/Yonsm/YoungHook

**Comment by blunden** [comment]
Any specific reason for the closure? :)

Don't get discouraged by the slow response times over here. Even simple pull requests can take months.

**Comment by Itaybre** [comment]
There are some issues, not working on all devices

**Comment by jankais3r** [comment]
Which device did you test this with? I am putting out bounty of $30 to get it to work with Unc0ver 5 on iPhone 11 or 2020 iPad Pro.

**Comment by shubham4500** [comment]
@jankais3r did it work on your 2020 iPad pro ?

**Comment by dlevi309** [comment]
Just saying for future reference if anyone is interested, HookUtil actually came from https://github.com/Matchstic/ReProvision/tree/master/iOS/HookUtil

**Pull request closed without merging**
