### PR TITLE
Add support for iOS11

### PR DESCRIPTION
**Pull request by mwpcheung**

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks :)

**Comment by McFlurriez** [comment]
I've been trying to get this working as well, did this actually work? Can anyone confirm on Charles/Burb? Also which iOS major and minor?

**Comment by samyk** [comment]
Doesn't seem to work for me. I'm trying to validate whether it's being injected into processes or not.

Additionally, I don't have `/usr/lib/libnetwork.dylib` on my iOS11 device (tweaks enabled via Electra on iOS 11.1.2) which the code seems to require, though I'm not sure if that's geared towards macOS.

**Comment by nabla-c0d3** [comment]
It should be working; I haven't checked but I'm guessing you won't see `/usr/lib/libnetwork.dylib` on an actual device because it's in the dyld shared cache ( http://iphonedevwiki.net/index.php/Dyld_shared_cache ). To see if the injection is working, you should look for a log that says "Substrate hook enabled".

**Comment by samyk** [comment]
Oh, interesting regarding the cache - thanks for that info!

I've created a pretty simple test app to validate using `NSURLConnection` ([https://samy.pl/o/nsurl.tgz]()). I'm performing a TLS MITMA through proxy and have custom CA installed on the phone. I get very strange results.

If I enable SSL Kill Switch, and install my TLS MITMA cert, regardless of whether the cert is trusted or not, the TLS connection always fails.

However, if I *disable* SSL Kill Switch, the connection works as long as the MITMA cert is trusted (in Settings->General->About->Certificate Trust Settings) - as expected. It fails if I untrust the cert as well, as expected.

I've loaded Frida up and can confirm `nw_tls_create_peer_trust` is getting called. Oddly, though, if I adjust the Frida __handler__ for `nw_tls_create_peer_trust` to return 0 (`errSecSuccess`) and have SSL Kill Switch disabled the cert untrusted, it also fails. But perhaps I'm setting that up incorrectly.

`__handlers__/libnetwork.dylib/nw_tls_create_peer_trust.js`:
```js
{ onLeave: function (log, retval, state) { retval.replace(0); } }
```

**Comment by samyk** [comment]
SKS is definitely running (see logs), and as mentioned in previous post, it *is* affecting TLS sessions, just not in the right way. Seems to be causing them to not complete even when I do have a cert supporting the MITMA.

It seems to fail here:
`Jul  1 21:40:07 the-titanic nsurl-request(libboringssl.dylib)[897] <Error>: Function boringssl_session_finish_handshake: line 2643 The peer was not authenticated. Disconnecting the connection.`

Oddly using Frida does not capture that function:
`frida-trace -U -i "*boringssl_*" nsurl-request`

Plenty of other functions are captured and hooked by Frida but not `boringssl_session_finish_handshake`. I've confirmed the function is in the .dylib in IDA
IDA libboringssl.dylib

That function also isn't in Google's boringssl, so clearly they have their own fork and I haven't found it available online. I'll have to see if the [license](https://github.com/google/boringssl/blob/master/LICENSE) requires them to open it up or not.

I've pulled logs while running my test app (and added some minor logs to SKS), and do see `Substrate hook enabled` (logs below matching `/nsurl|ssl|substrate/i`):
```
1288   :        SBLayoutRolePrimary = <SBDeviceApplicationSceneEntity: 0x1c0284fb0; ID: pl.samy.nsurl-request; layoutRole: primary>;
1304   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: Submitting new job for "pl.samy.nsurl-request" on behalf of <BKProcess: 0x10123bbf0; SpringBoard; com.apple.springboard; pid: 879; agency: SystemShell; visibility: foreground; task: running>
1305   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: Submitted job with label: UIKitApplication:pl.samy.nsurl-request[0xe9d3][442]
1307   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Adding client: <BKProcessInfoServerClient: 0x101222800; pid: 879>
1308   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Setting jetsam priority to 10 [0x10000]
1310   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: Now tracking process <BKProcess: 0x1011487b0; nsurl-request; pl.samy.nsurl-request; pid: 897; agency: SystemApp; visibility: none; task: running; hostpid: 879> with host <BKProcess: 0x10123bbf0; SpringBoard; com.apple.springboard; pid: 879; agency: SystemShell; visibility: foreground; task: running>
1311   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [SpringBoard:879] Attempting to acquire assertion for nsurl-request:897: <BKProcessAssertion: 0x10113f170; "UIApplicationLaunch" (activation:inf); id:\M-b\M^@\M-&0D1C43BA3D81>
1312   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Add assertion: <BKProcessAssertion: 0x10113f170; id: 879-1F4968EB-1992-46A8-8F81-0D1C43BA3D81; name: UIApplicationLaunch; state: active; reason: activation; duration: infs> {
1315   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Activate assertion: <BKProcessAssertion: 0x10113f170; "UIApplicationLaunch" (activation:inf); id:\M-b\M^@\M-&0D1C43BA3D81>
1316   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, wantsForegroundResourcePriority, preventSuspendOnSleep (assertion 0x10113f170 added: preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, wantsForegroundResourcePriority, preventSuspendOnSleep; removed: (none))
1317   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Setting jetsam priority to 10 [0x10100]
1318   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] setpriority success for resource GPU to PRIO_DARWIN_GPU_ALLOW
1319   :Jul  1 21:40:06 the-titanic assertiond[442] <Notice>: [nsurl-request:897] setpriority success for resource CPU to default (0)
1320   :Jul  1 21:40:06 the-titanic SpringBoard(WiFiPicker)[879] <Notice>: WIFI PICKER [pl.samy.nsurl-request]: isProcessLaunch: 1,    isForegroundActivation: 1,     isForegroundDeactivation: 0
1321   :Jul  1 21:40:06 the-titanic SpringBoard(AssertionServices)[879] <Notice>: [pl.samy.nsurl-request] Bootstrap complete with label: UIKitApplication:pl.samy.nsurl-request[0xe9d3][442]
1322   :Jul  1 21:40:06 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [FBProcessManager] Adding: <FBApplicationProcess: 0x10a24e1e0; nsurl-request (pl.samy.nsurl-request); pid: 897>
1323   :Jul  1 21:40:06 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [pl.samy.nsurl-request] Setting deactivation reasons to: 'systemAnimation' for reason: scene settings update - settings are eligible for deactivation reasons.
1325   :Jul  1 21:40:06 the-titanic SpringBoard[879] <Notice>: Application process state changed for pl.samy.nsurl-request: <SBApplicationProcessState: 0x1c5027ca0; pid: 897; taskState: Running; visibility: Unknown>
1326   :Jul  1 21:40:06 the-titanic mediaserverd(CoreMedia)[521] <Notice>: -CMSessionMgr- CMSessionMgrHandleApplicationStateChange: CMSession: Client pl.samy.nsurl-request with pid '897' is now Foreground Running. Background entitlement: NO
1332   :    SBApplicationStateDisplayIDKey = "pl.samy.nsurl-request";
1336   :Jul  1 21:40:06 the-titanic symptomsd(SymptomEvaluator)[481] <Notice>: 897 pl.samy.nsurl-request: ForegroundRunning (most elevated: ForegroundRunning)
1337   :Jul  1 21:40:06 the-titanic symptomsd(SymptomEvaluator)[481] <Notice>: Entry, display name pl.samy.nsurl-request uuid AEA017C5-75E0-3012-B972-F13775CF8F47 pid 897 isFront 1
1338   :Jul  1 21:40:06 the-titanic symptomsd(SymptomEvaluator)[481] <Notice>: Continue with bundle name pl.samy.nsurl-request, is front 1
1339   :Jul  1 21:40:06 the-titanic symptomsd(SymptomEvaluator)[481] <Notice>: pl.samy.nsurl-request: Foreground: true
1343   :Jul  1 21:40:06 the-titanic nsurl-request(TweakInject.dylib)[897] <Notice>: Injecting /Library/TweakInject/SSLKillSwitch2.dylib into pl.samy.nsurl-request
1344   :Jul  1 21:40:06 the-titanic nsurl-request(SSLKillSwitch2.dylib)[897] <Notice>: === SSL Kill Switch 2: SSLKS1
1345   :Jul  1 21:40:06 the-titanic nsurl-request(SSLKillSwitch2.dylib)[897] <Notice>: === SSL Kill Switch 2: SSLKS2
1346   :Jul  1 21:40:06 the-titanic nsurl-request(SSLKillSwitch2.dylib)[897] <Notice>: === SSL Kill Switch 2: Preference set to 1.
1347   :Jul  1 21:40:06 the-titanic nsurl-request(SSLKillSwitch2.dylib)[897] <Notice>: === SSL Kill Switch 2: Substrate hook enabled.
1348   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] workspaceConnectedWithTaskPortRight: received task port
1349   :Jul  1 21:40:07 the-titanic nsurl-request(libAccessibility.dylib)[897] <Notice>: Retrieving resting unlock: 0
1463   :Jul  1 21:40:07 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [pl.samy.nsurl-request] Setting deactivation reasons to: '(none)' for reason: updateAllScenesForBand - Assertion removed.
1491   :Jul  1 21:40:07 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [pl.samy.nsurl-request] Sending scene action [Logical Activate] through WorkspaceServer: 0x1c4480370
1492   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [SpringBoard:879] Attempting to acquire assertion for nsurl-request:897: <BKProcessAssertion: 0x10114a640; "Resume" (activation:inf); id:\M-b\M^@\M-&6DEDE9E7ABFB>
1493   :Jul  1 21:40:07 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [pl.samy.nsurl-request] Sending scene action [SceneLifecycleEventOnly] through WorkspaceServer: 0x1c4480370
1494   :Jul  1 21:40:07 the-titanic SpringBoard(FrontBoard)[879] <Notice>: [pl.samy.nsurl-request] Sending scene action [SceneLifecycleEventOnly] through WorkspaceServer: 0x1c4480370
1495   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Add assertion: <BKProcessAssertion: 0x10114a640; id: 879-1E0FFF88-2BC6-4BB8-86EA-6DEDE9E7ABFB; name: Resume; state: active; reason: activation; duration: infs> {
1498   :Jul  1 21:40:07 the-titanic SpringBoard[879] <Notice>: Application process state changed for pl.samy.nsurl-request: <SBApplicationProcessState: 0x1c4433a60; pid: 897; taskState: Running; visibility: Foreground>
1499   :Jul  1 21:40:07 the-titanic SpringBoard[879] <Notice>: Application process state changed for pl.samy.nsurl-request: <SBApplicationProcessState: 0x1c5027ca0; pid: 897; taskState: Running; visibility: Foreground>
1500   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Activate assertion: <BKProcessAssertion: 0x10114a640; "Resume" (activation:inf); id:\M-b\M^@\M-&6DEDE9E7ABFB>
1501   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [SpringBoard:879] Attempting to acquire assertion for nsurl-request:897: <BKProcessAssertion: 0x101240090; "Deliver Message" (suspend:10s); id:\M-b\M^@\M-&972A8C1209F4>
1502   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Add assertion: <BKProcessAssertion: 0x101240090; id: 879-4C684D3A-2568-453A-B10A-972A8C1209F4; name: "Deliver Message"; state: active; reason: suspend; duration: 10.0s> {
1506   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Activate assertion: <BKProcessAssertion: 0x101240090; "Deliver Message" (suspend:10s); id:\M-b\M^@\M-&972A8C1209F4>
1507   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Setting jetsam priority to 10 [0x10300]
1509   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Deactivate assertion: <BKProcessAssertion: 0x10113f170; "UIApplicationLaunch" (activation:inf); id:\M-b\M^@\M-&0D1C43BA3D81>
1510   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] dump all assertions HWM:3 (deactivateAssertion): {
1513   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Scheduling allow-idle-sleep timer with interval: 180.0
1514   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] New process assertion state; preventSuspend, preventThrottleDownUI, preventThrottleDownCPU, preventSuspendOnSleep (assertion 0x10113f170 added: (none); removed: wantsForegroundResourcePriority)
1515   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Remove assertion: <BKProcessAssertion: 0x10113f170; "UIApplicationLaunch" (activation:inf); id:\M-b\M^@\M-&0D1C43BA3D81>
1533   :Jul  1 21:40:07 the-titanic nsurl-request(HangTracer)[897] <Notice>: refreshPreferences: HangTracerEnabled: 0
1534   :Jul  1 21:40:07 the-titanic nsurl-request(HangTracer)[897] <Notice>: refreshPreferences: HangTracerDuration: 500
1535   :Jul  1 21:40:07 the-titanic nsurl-request(HangTracer)[897] <Notice>: refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
1536   :Jul  1 21:40:07 the-titanic nsurl-request[897] <Notice>: === nsurl-request: Requesting URL.
1538   :Jul  1 21:40:07 the-titanic SpringBoard[879] <Notice>: Front display did change: <SBApplication: 0x1c41db030; pl.samy.nsurl-request>
1540   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: Faulting in NSHTTPCookieStorage singleton
1541   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: Faulting in CFHTTPCookieStorage singleton
1542   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: Creating default cookie storage with default identifier
1543   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC Enabling TLS [1:0x1c416ef40]
1544   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Start [1:0x1c416ef40]
1545   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: Task <BC2BDAE5-3589-418A-AD35-CD108FB728F2>.<0> setting up Connection 1
1550   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Connected [1:0x1c416ef40]: Err(16)
1551   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Event [1:0x1c416ef40]: 1
1552   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC Enabling TLS [1:0x1c416ef40]
1553   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TLS Event [1:0x1c416ef40]: 1, Pending(0)
1554   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TLS Event [1:0x1c416ef40]: 2, Pending(0)
1555   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TLS Event [1:0x1c416ef40]: 11, Pending(0)
1556   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TLS Event [1:0x1c416ef40]: 12, Pending(0)
1557   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TLS Event [1:0x1c416ef40]: 14, Pending(0)
1558   :Jul  1 21:40:07 the-titanic nsurl-request(libboringssl.dylib)[897] <Error>: Function boringssl_session_finish_handshake: line 2643 The peer was not authenticated. Disconnecting the connection.
1559   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Event [1:0x1c416ef40]: 3
1560   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Cancel [1:0x1c416ef40]
1561   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9810)
1562   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Error>: Task <BC2BDAE5-3589-418A-AD35-CD108FB728F2>.<0> HTTP load failed (error code: -1200 [3:-9810])
1563   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Notice>: TIC TCP Conn Destroyed [1:0x1c416ef40]
1564   :Jul  1 21:40:07 the-titanic nsurl-request(CFNetwork)[897] <Error>: NSURLConnection finished with error - code -1200
1565   :Jul  1 21:40:07 the-titanic nsurl-request(AccessibilitySettingsLoader)[897] <Notice>: Sending initial safe area update
1567   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Deactivate assertion: <BKProcessAssertion: 0x101240090; "Deliver Message" (suspend:10s); id:\M-b\M^@\M-&972A8C1209F4>
1568   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] dump all assertions HWM:3 (deactivateAssertion): {
1570   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Setting jetsam priority to 10 [0x10100]
1571   :Jul  1 21:40:07 the-titanic assertiond[442] <Notice>: [nsurl-request:897] Remove assertion: <BKProcessAssertion: 0x101240090; "Deliver Message" (suspend:10s); id:\M-b\M^@\M-&972A8C1209F4>
```

**Comment by nVisium-Kevin-Cody** [comment]
FWIW, I sent a message to @samyk out-of-band, but SKS2 seems to be working for my iOS 11.1, Electra JB, iPhone 7 Plus. I've done a number of tests including bypassing known cert pinning with a trusted proxy CA installed, proxying without a trusted CA installed, etc. I've also done the control tests of doing the above with SKS2 toggled-off. Let me know if I can help connect any dots with logs, configs, more details, etc.

Outside of the above, I sincerely thank @nabla-c0d3 and @samyk for continuing the push forward and enabling folks like me to focus on testing AppSec. Cheers!

**Comment by samyk** [comment]
I also tested an app that @nVisium-Kevin-Cody has used successfully with SKS2 and am getting the same error, though I'm on iOS 11.1.2
`(libboringssl.dylib)[1167] <Error>: Function boringssl_session_finish_handshake: line 2643 The peer was not authenticated. Disconnecting the connection.`

**Comment by nVisium-Kevin-Cody** [comment]
As I keep going down this wormhole, things are making less-and-less sense. My original device (which I referenced above) actually does not capture the `Substrate hook enabled` within the console, even though it *is* effective in bypassing TLS Pinning. That said, @samyk's nsurl app does not work, even on the device that seems to be functioning well.

Also, I recently jailbroke a different iOS device, and am now experiencing the same exact bevy of issues that @samyk noted above. Even with the same application which SKS2 helped with previously, I am unable to bypass pinning. Furthermore, the original device did not require workarounds for moving tweaks and dylibs; however, this device did. I tried several combinations of symlinks, copied files, etc.

Thus, I have to agree that things tend to be a little alloverthemap.

**Pull request merged**
